---
- import_playbook: playbook-spark-stop.yml

- hosts: all
  become: no
  any_errors_fatal: true
  gather_facts: no
  vars_files:
      - vars.yaml

  tasks:
    - name: Remove spark folders
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ spark_home_dir }}"
