---
- hosts: spark_master
  become: no
  any_errors_fatal: true
  gather_facts: no
  vars_files:
    - vars.yaml

  tasks:
  - name: Start Spark
    ansible.builtin.shell: |
      {{spark_home_dir}}/sbin/start-all.sh
    args:
      executable: /bin/bash
