---
- hosts: all
  become: no
  any_errors_fatal: true
  gather_facts: no
  vars_files:
      - vars.yaml

  tasks:
    - name: Configure Spark with HDFS Hadoop core-site configuration
      ansible.builtin.template:
        src: templates/hadoop/core-site.xml.j2
        dest: "{{spark_conf_dir}}/core-site.xml"

    - name: Configure Spark with HDFS Hadoop hdfs site configuration
      ansible.builtin.template:
        src: templates/hadoop/hdfs-site.xml.j2
        dest: "{{spark_conf_dir}}/hdfs-site.xml"

    - name: Configure Spark with HDFS Hadoop workers configuration
      ansible.builtin.template:
        src: templates/hadoop/workers.j2
        dest: "{{spark_conf_dir}}/workers"

    - name: Configure Spark with HDFS Hadoop yarn configuration
      ansible.builtin.template:
        src: templates/hadoop/yarn-site.xml.j2
        dest: "{{spark_conf_dir}}/yarn-site.xml"

    - name: Configure Spark scheduler
      ansible.builtin.template:
        src: templates/spark/fairscheduler.xml.j2
        dest: "{{spark_conf_dir}}/fairscheduler.xml"

    - name: Configure Spark log4j2
      ansible.builtin.template:
        src: templates/spark/log4j2.properties.j2
        dest: "{{spark_conf_dir}}/log4j2.properties"

    - name: Configure Spark metrics
      ansible.builtin.template:
        src: templates/spark/metrics.properties.j2
        dest: "{{spark_conf_dir}}/metrics.properties"

    - name: Configure Spark defaults
      ansible.builtin.template:
        src: templates/spark/spark-defaults.conf.j2
        dest: "{{spark_conf_dir}}/spark-defaults.conf"

    - name: Configure Spark envs
      ansible.builtin.template:
        src: templates/spark/spark-env.sh.j2
        dest: "{{spark_conf_dir}}/spark-env.sh"