#! /usr/local/bin/ansible-playbook

- import_playbook: playbook-hdfs-start.yml

- hosts: hdfs_namenode
  become: no
  gather_facts: no
  any_errors_fatal: true
  vars_files:
    - vars.yaml

  tasks:
    - name: Create dataset path on HDFS
      ansible.builtin.shell: |
        {{hadoop_home_dir}}/bin/hdfs dfs -mkdir -p {{hdfs_dataset_path}}
      args:
        executable: /bin/bash

    - name: Upload dataset to HDFS
      ansible.builtin.shell: |
        {{hadoop_home_dir}}/bin/hadoop fs -put {{local_dataset_path}}/{{item}} {{hdfs_dataset_path}}/
      args:
        executable: /bin/bash
      with_items:
        - "{{ dataset_files }}"
