---
- hosts: jupyter_service
  become: no
  any_errors_fatal: true
  gather_facts: no
  vars_files:
    - vars.yaml

  tasks:
  - name: Stop WORKER processes
    set_fact:
      process_to_kill: "'jupyter-notebook|tjupyter|start-jupyter'"

  - name: Run tasks to stop Jupyter processes
    include_tasks: tasks/task-stop-process.yml
