#! /usr/local/bin/ansible-playbook

- hosts: hdfs_namenode
  become: no
  gather_facts: no
  any_errors_fatal: true
  vars_files:
    - vars.yaml

  tasks:
    # Specially in IOException situations safe mode is enabled
    - name: Turn off safe mode
      ansible.builtin.shell: |
        {{hadoop_home_dir}}/bin/hdfs dfsadmin -safemode leave
      args:
        executable: /bin/bash

    - name: Rebalance HDFS
      ansible.builtin.shell: |
        {{hadoop_home_dir}}/bin/hdfs balancer -threshold 1
      args:
        executable: /bin/bash