---
- import_playbook: playbook-jupyter-stop.yml
- import_playbook: playbook-spark-stop.yml
- import_playbook: playbook-hdfs-stop.yml

- hosts: all
  become: no
  any_errors_fatal: true
  gather_facts: no
  vars_files:
      - vars.yaml

  tasks:
    - name: Stop specified processes
      shell: "pkill -9 -f '{{ item }}' || true"
      args:
        executable: /bin/bash
      loop:
        - org.apache.hadoop
        - org.apache.spark
      failed_when: false